<!DOCTYPE html>
<html lang="en">
    
    


    <head>
    <link href="https://gmpg.org/xfn/11" rel="profile">
    <meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<!-- Enable responsiveness on mobile devices -->
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">
<meta name="generator" content="Hugo 0.80.0" />

    
    
    

<title>Session 04 - Instrumental Variables • 2020-II Statistical Modeling and Causal Inference Tutorial</title>


<meta name="twitter:card" content="summary"/>
<meta name="twitter:title" content="Session 04 - Instrumental Variables"/>
<meta name="twitter:description" content="Welcome Today we will have a look at instrumental variables. We will explore encouragement experimental designs and how IVs can be used in observational data settings. Additionally, we will learn how to calculate our LATE manually with the wald estimator and in R with two-stage square least regressions through ivreg
 Measuring the effect of mosquito net use on malaria infection Imagine that the organization you work for is laying out a project to distribute mosquito nets to help combat malaria transmitions."/>

<meta property="og:title" content="Session 04 - Instrumental Variables" />
<meta property="og:description" content="Welcome Today we will have a look at instrumental variables. We will explore encouragement experimental designs and how IVs can be used in observational data settings. Additionally, we will learn how to calculate our LATE manually with the wald estimator and in R with two-stage square least regressions through ivreg
 Measuring the effect of mosquito net use on malaria infection Imagine that the organization you work for is laying out a project to distribute mosquito nets to help combat malaria transmitions." />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://seramirezruiz.github.io/2020-fall-stats2/scripts/lab_5_ivs/" />
<meta property="article:published_time" content="2020-09-22T00:00:00+00:00" />
<meta property="article:modified_time" content="2020-09-22T00:00:00+00:00" /><meta property="og:site_name" content="Statistical Modeling and Causal Inference Tutorial | 2020-II" />


    


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css">








<link rel="stylesheet" href="/2020-fall-stats2/scss/hyde-hyde.71157e768c4e111a23c3531b95e0cbb59bbef3c9e6901d36247cb53d6b6be258.css" integrity="sha256-cRV&#43;doxOERojw1MbleDLtZu&#43;88nmkB02JHy1PWtr4lg=">


<link rel="stylesheet" href="/2020-fall-stats2/scss/print.2744dcbf8a0b2e74f8a50e4b34e5f441be7cf93cc7de27029121c6a09f9e77bc.css" integrity="sha256-J0Tcv4oLLnT4pQ5LNOX0Qb58&#43;TzH3icCkSHGoJ&#43;ed7w=" media="print">



    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/apple-touch-icon-144-precomposed.png">
    <link rel="shortcut icon" href="/favicon.png">
    
    

</head>


    <body class=" ">
    

    <script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML"></script>
    
    <script type="text/x-mathjax-config">
    MathJax.Hub.Config({
        tex2jax: {
            inlineMath: [ ['$','$'], ["\\(","\\)"] ],
            displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
            processEscapes: true,
            processEnvironments: true
        },
        // Center justify equations in code and markdown cells. Elsewhere
        // we use CSS to left justify single line equations in code cells.
        displayAlign: 'center',
        "HTML-CSS": {
            styles: {'.MathJax_Display': {"margin": 0}},
            linebreaks: { automatic: true }
        }
    });
    </script>


<div class="sidebar">
  <div class="container ">
    <div class="sidebar-about">
      <span class="site__title">
        <a href="https://seramirezruiz.github.io/2020-fall-stats2">
        
          2020-II Statistical Modeling and Causal Inference Tutorial
        
        </a>
      </span>
      
      
      <p class="site__description">
        
      </p>
    </div>
    <div class="collapsible-menu">
      <input type="checkbox" id="menuToggle">
      <label for="menuToggle">2020-II Statistical Modeling and Causal Inference Tutorial</label>
      <div class="menu-content">
        <div>
	<ul class="sidebar-nav">
		 
		 
			 
				<li>
					<a href="/2020-fall-stats2/about/"><i class='fa fa-info'></i>
						<span>About</span>
					</a>
				</li>
			 
		 
			 
				<li>
					<a href="/2020-fall-stats2/scripts/"><i class='fa fa-code'></i>
						<span>Scripts</span>
					</a>
				</li>
			 
		 
			 
				<li>
					<a href="/2020-fall-stats2/slides/"><i class='fa fa-laptop'></i>
						<span>Slides</span>
					</a>
				</li>
			 
		
	</ul>
</div>

        <section class="social">
	
	<a href="https://twitter.com/seramirezruiz" rel="me"><i class="fab fa-twitter fa-lg" aria-hidden="true"></i></a>
	
	
	
	
	<a href="https://github.com/seramirezruiz" rel="me"><i class="fab fa-github fa-lg" aria-hidden="true"></i></a>
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	<a href="mailto:ramirez-ruiz@hertie-school.org" rel="me"><i class="fas fa-at fa-lg" aria-hidden="true"></i></a>
	
	
	
	
</section>

      </div>
    </div>
    
<div class="copyright">
  &copy; 2020 - 2021 Sebastian Ramirez Ruiz
  
    <a href="https://creativecommons.org/licenses/by-sa/4.0">CC BY-SA 4.0</a>
  
</div>



  </div>
</div>

        <div class="content container">
            
    
<article>
  <header>
    <h1>Session 04 - Instrumental Variables</h1>
    
    
<div class="post__meta">
    
    
      <i class="fas fa-calendar-alt"></i> Sep 22, 2020
    
    
    
    
    
    <br/>
    <i class="fas fa-clock"></i> 8 min read
</div>


  </header>
  
  
  <div class="post">
    
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>


<div id="welcome" class="section level2">
<h2>Welcome</h2>
<p>Today we will have a look at instrumental variables. We will explore encouragement experimental designs and how IVs can be used in observational data settings. Additionally, we will learn how to calculate our LATE manually with the wald estimator and in R with two-stage square least regressions through <code>ivreg</code></p>
<hr />
</div>
<div id="measuring-the-effect-of-mosquito-net-use-on-malaria-infection" class="section level2">
<h2>Measuring the effect of mosquito net use on malaria infection</h2>
<p>Imagine that the organization you work for is laying out a project to distribute mosquito nets to help combat malaria transmitions. You are in charge of running the impact evaluation of this program. You realize that it is unethical to randomize who receives the nets, so you consider an encouragement design. You decide to randomly select five villages out of the ten to send SMS reminders every night encouraging them to use the mosquito nets. (This example is using simulated data)</p>
<div class="figure">
<img src="https://raw.githubusercontent.com/seramirezruiz/stats-ii-lab/master/Session%205/data/dag_program.png" />

</div>
<p><br> <br></p>
<hr />
<p><br> <br></p>
<div id="assumptions" class="section level3">
<h3>Assumptions</h3>
<p>For this evaluation to render credible results we need to fulfill a certain set of assumtions:</p>
<p><strong>a) Relevance:</strong> Also known as non-zero average encouragement effect. Does our <span class="math inline">\(Z\)</span> create variation in our <span class="math inline">\(D\)</span>? In other words, is the mosquito net use different under the encouragement group? (Statistically testable)</p>
<p><strong>b) Exogeneity/Ignorability of the instrument:</strong> Potential outcomes and treatments are independent of <span class="math inline">\(Z\)</span>. In this case given by out randomization of encouragement by villages.</p>
<p><strong>c) Exclusion restriction:</strong> The instrument only affects the outcome via the treatment. In other words, there are no alternative paths through which our SMS can have an effect on malaria infections other that the use of the mosquito nets.</p>
<p><strong>d) Monotonicity:</strong> No defiers. We assume that non-compliers fall in the camp of always- and never-takers. We would not expect subjects who when encouraged would not use the nets, but would use them if they did not recieve the SMS reminder. <br></p>
<hr />
<div id="loading-our-packages-and-data" class="section level4">
<h4>loading our packages and data</h4>
<pre class="r"><code>library(dplyr) # for data wrangling
library(readr) # for loading the .csv data
library(ggplot2) # for creating plots
library(summarytools) # for ctable()
library(stargazer) # for formatting model output
library(kableExtra) # for formatting data frames
library(AER) # for ivreg()
library(tidyr) # for pivot_wider()

set.seed(123) # for consistent results

eval_data &lt;- readr::read_csv(&quot;https://raw.githubusercontent.com/seramirezruiz/stats-ii-lab/master/Session%205/data/evaluation_data.csv&quot;) # loading simulated data frame of the intervention</code></pre>
<hr />
</div>
</div>
</div>
<div id="exploring-our-results" class="section level2">
<h2>Exploring our results</h2>
<p>You receive the results of your intervention from the M&amp;E officers. This is what they look like:</p>
<div class="figure">
<img src="https://raw.githubusercontent.com/seramirezruiz/stats-ii-lab/master/Session%205/data/compliance.png" />

</div>
<pre class="r"><code>summarytools::st_options(footnote = NA) # to get rid of the footnote of ctable
print(summarytools::ctable(eval_data$net_use, eval_data$sms, prop = &quot;n&quot;), 
      method = &quot;render&quot;) # include results = &quot;asis&quot; to view html in the knitted file</code></pre>
<div class="container st-container">
<h3>Cross-Tabulation</h3>
<h4>net_use * sms</h4>
<strong>Data Frame</strong>: eval_data
<br/>
<table class="table table-bordered st-table st-table-bordered st-cross-table ">
<thead>
<tr>
<th></th>
<th colspan="2" align="center" class="st-protect-top-border">sms</th>
<th colspan="1"></th>
</tr>
<tr>
<td align="center">
<strong>net_use</strong>
</td>
<th colspan="1" align="center">0</th>
<th colspan="1" align="center">1</th>
<th colspan="1" align="center">Total</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<strong align="center">0</strong>
</td>
<td>
<span>335</span>
</td>
<td>
<span>110</span>
</td>
<td>
<span>445</span>
</td>
</tr>
<tr>
<td>
<strong align="center">1</strong>
</td>
<td>
<span>165</span>
</td>
<td>
<span>390</span>
</td>
<td>
<span>555</span>
</td>
</tr>
<tr>
<td>
<strong align="center">Total</strong>
</td>
<td>
<span>500</span>
</td>
<td>
<span>500</span>
</td>
<td>
<span>1000</span>
</td>
</tr>
</tbody>
</table>
</div>
<p>
<center>
<strong>LET'S EXPLORE COMPLIANCE TYPES FROM THIS TABLE TOGETHER</strong>
</center>
<p><br> a) Where are our compliers and non-compliers?<br> b) How many people were encouraged via SMS, but did not use the net?<br> c) How many people were not encouraged via SMS, yet they utilized the net?</p>
<p><br> <br></p>
<hr />
<p>We can also utilize dplyr to check the average malaria on each stratum:</p>
<pre class="r"><code>eval_data %&gt;%
  dplyr::group_by(net_use, sms) %&gt;% #group our data on the tratment and instrument
  dplyr::summarize(avg = mean(malaria)) %&gt;% #get the aveage value of malaria
  dplyr::mutate(avg = round(avg, 2)) %&gt;% #round the avg to 2 decimal places
  tidyr::pivot_wider(names_from = sms, values_from = avg) %&gt;% #convert to wide format
  knitr::kable() %&gt;% #turn to kable
  kableExtra::kable_styling() %&gt;% 
  kableExtra::add_header_above(c(&quot;&quot;, &quot;sms&quot; = 2)) #add header for sms</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="border-bottom:hidden" colspan="1">
</th>
<th style="border-bottom:hidden; padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
sms
</div>
</th>
</tr>
<tr>
<th style="text-align:right;">
net_use
</th>
<th style="text-align:right;">
0
</th>
<th style="text-align:right;">
1
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.73
</td>
<td style="text-align:right;">
0.55
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.05
</td>
<td style="text-align:right;">
0.08
</td>
</tr>
</tbody>
</table>
<p><br></p>
<hr />
<p>Additionally, we can explore our data visually to check beyond compliance and see in which groups malaria was present. In this case, we are dealing with binary outcomes. That is, you can either be or not be infected, which are represented by the color dimension in different groups.</p>
<pre class="r"><code>ggplot(eval_data, aes(x = factor(sms), 
                      y = factor(net_use), 
                      color = factor(malaria))) +
  geom_point() +
  geom_jitter() +
  theme_minimal() +
  scale_x_discrete(labels = c(&quot;SMS = 0&quot;, &quot;SMS = 1&quot;)) +
  scale_y_discrete(labels = c(&quot;NET = 0&quot;, &quot;NET = 1&quot;)) +
  scale_color_discrete(labels = c(&quot;Not infected&quot;, &quot;Infected&quot;)) +
  labs(x = &quot;Encouragement&quot;,
       y = &quot;Treatment&quot;,
       color = &quot;&quot;)</code></pre>
<p><img src="/scripts/lab_5_IVs_files/figure-html/unnamed-chunk-4-1.png" width="672" style="display: block; margin: auto;" /> <br></p>
<hr />
<p><br></p>
</div>
<div id="exploring-our-set-up" class="section level2">
<h2>Exploring our set-up</h2>
<div id="lets-check-whether-sms-encouragement-is-a-strong-instrument" class="section level4">
<h4>Let's check whether SMS encouragement is a strong instrument</h4>
<p>In other words, we are looking at the relevance assumption. Does our SMS encouragement create changes in our mosquito net use?</p>
<pre class="r"><code>summary(lm(net_use ~ sms, eval_data))</code></pre>
<pre><code>## 
## Call:
## lm(formula = net_use ~ sms, data = eval_data)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
##  -0.78  -0.33   0.22   0.22   0.67 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.33000    0.01984   16.64   &lt;2e-16 ***
## sms          0.45000    0.02805   16.04   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.4436 on 998 degrees of freedom
## Multiple R-squared:  0.205,  Adjusted R-squared:  0.2042 
## F-statistic: 257.3 on 1 and 998 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Economists have established as a &quot;rule-of-thumb&quot; for the case of a single endogenous regressor to be considered a strong instrument should have a <strong>F-statistic</strong> <a href="#fn1" class="footnoteRef" id="fnref1"><sup>1</sup></a> greater than 10. From this regression, we can see that SMS encouragement is a strong instrument. Additionally, the substantive read in this case is that only 33% of those who did not receive the SMS utilized the mosquito nets, where as 78% of those who got the SMS encouragement did. <br> <br> <br> <br> <br></p>
<hr />
</div>
<div id="lets-gather-a-naïve-estimate-of-mosquito-net-use-and-malaria-infection." class="section level4">
<h4>Let's gather a naïve estimate of mosquito net use and malaria infection.</h4>
<p>
<p>Also, why do you think we call this a naïve estimate?</p>
<pre class="r"><code>naive_model &lt;- lm(malaria ~ net_use, eval_data)
summary(naive_model)</code></pre>
<pre><code>## 
## Call:
## lm(formula = malaria ~ net_use, data = eval_data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.68315 -0.06847 -0.06847  0.31685  0.93153 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.68315    0.01722   39.67   &lt;2e-16 ***
## net_use     -0.61468    0.02312  -26.59   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.3633 on 998 degrees of freedom
## Multiple R-squared:  0.4147, Adjusted R-squared:  0.4141 
## F-statistic:   707 on 1 and 998 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><br> <br> <br> <br> <br></p>
<hr />
</div>
<div id="lets-gather-our-intent-to-treat-effect-itt" class="section level4">
<h4>Let's gather our intent-to-treat effect (ITT)</h4>
<p>
<p>This is the effect that our SMS encouragement had on malaria infections. <span class="math inline">\(ITT = E(Malaria_i|SMS=1) - E(Malaria_i|SMS=0)\)</span>. What does this tell us?</p>
<pre class="r"><code>itt_model &lt;- lm(malaria ~ sms, eval_data)
summary(itt_model)</code></pre>
<pre><code>## 
## Call:
## lm(formula = malaria ~ sms, data = eval_data)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -0.504 -0.180 -0.180  0.496  0.820 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.50400    0.01996   25.25   &lt;2e-16 ***
## sms         -0.32400    0.02823  -11.48   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.4463 on 998 degrees of freedom
## Multiple R-squared:  0.1166, Adjusted R-squared:  0.1157 
## F-statistic: 131.8 on 1 and 998 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><br> <br> <br> <br> <br></p>
<hr />
</div>
</div>
<div id="lets-gather-out-local-average-treatment-effect-late" class="section level2">
<h2>Let's gather out local average treatment effect (LATE)</h2>
<p>We have several options for this:</p>
<ul>
<li><strong>Wald Estimator</strong> We can calculate this by hand. Let's try that now, using the values from the table. We can also calculate the average malaria rates among those who did and did not receive an SMS (no SMS = 0.504, yes SMS = 0.18). <span class="math display">\[LATE = \frac{cov(Y_i,Z_i)}{cov(D_i,Z_i)}\]</span></li>
</ul>
<table class="table table-bordered st-table st-table-bordered st-cross-table ">
<thead>
<tr>
<th>
</th>
<th colspan="2" align="center" class="st-protect-top-border">
sms
</th>
<th colspan="1">
</th>
</tr>
<tr>
<td align="center">
<strong>net_use</strong>
</td>
<th colspan="1" align="center">
0
</th>
<th colspan="1" align="center">
1
</th>
<th colspan="1" align="center">
Total
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<strong align="center">0</strong>
</td>
<td>
<span>335</span>
</td>
<td>
<span>110</span>
</td>
<td>
<span>445</span>
</td>
</tr>
<tr>
<td>
<strong align="center">1</strong>
</td>
<td>
<span>165</span>
</td>
<td>
<span>390</span>
</td>
<td>
<span>555</span>
</td>
</tr>
<tr>
<td>
<strong align="center">Total</strong>
</td>
<td>
<span>500</span>
</td>
<td>
<span>500</span>
</td>
<td>
<span>1000</span>
</td>
</tr>
</tbody>
</table>
<p><strong>Let's take a look at our numerator</strong> <span class="math inline">\(cov(Y_i,Z_i)\)</span> <br></p>
<blockquote>
<p><span class="math inline">\(E(Y|Z = 1)\)</span> = 0.18 <br> <span class="math inline">\(E(Y|Z = 0)\)</span> = 0.504 <br></p>
</blockquote>
<p><strong>Let's take a look at our denominator</strong> <span class="math inline">\(cov(D_i,Z_i)\)</span> <br></p>
<blockquote>
<p><span class="math inline">\(E(D ∣ Z = 1) = \frac{390}{(390 + 110)} = 0.78\)</span> <br> <span class="math inline">\(E(D ∣ Z = 0) = \frac{165}{(165 + 335)} = 0.33\)</span> <br></p>
</blockquote>
<p><strong>We can calculate our LATE</strong> <span class="math display">\[LATE =  \frac{(0.18 - 0.504)}{(0.78 - 0.33)} = -0.72\]</span><br></p>
<hr />
<ul>
<li><strong>Two-stage Least Squares (2SLS)</strong>. We will learn how to do this with ivreg(), which is part of the <code>AER</code> package. It fits instrumental-variable regression through two-stage least squares. The syntax is the following:</li>
</ul>
<center>
ivreg(outcome ~ treatment | instrument, data)
</center>
<p>
<pre class="r"><code>late_model &lt;- AER::ivreg(malaria ~ net_use | sms, data = eval_data)
summary(late_model)</code></pre>
<pre><code>## 
## Call:
## AER::ivreg(formula = malaria ~ net_use | sms, data = eval_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -0.7416 -0.0216 -0.0216  0.2584  0.9784 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.74160    0.03089   24.00   &lt;2e-16 ***
## net_use     -0.72000    0.05159  -13.96   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.3671 on 998 degrees of freedom
## Multiple R-Squared: 0.4025,  Adjusted R-squared: 0.4019 
## Wald test: 194.8 on 1 and 998 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>
<center>
What is the substantive reading of these results?
</center>
<p><br> <br> <br> <br> <br></p>
<hr />
</div>
<div id="mechanics-behing-two-stage-least-squares-2sls" class="section level2">
<h2>Mechanics behing two-stage least squares (2SLS)</h2>
<p>
<img src="https://raw.githubusercontent.com/seramirezruiz/stats-ii-lab/master/Session%205/data/instrumental-variables.gif" />
<p>
<p>What ivreg() is doing in the background is the following:</p>
<pre class="r"><code>net_use_hat &lt;- lm(net_use ~ sms, eval_data)$fitted.values # get fitted values from first stage (the part of x that is exogenously driven by z)
summary(lm(eval_data$malaria ~ net_use_hat)) # run second stage with instrumented x (careful, the standard errors are wrong; better use ivreg() from AER instead)</code></pre>
<pre><code>## 
## Call:
## lm(formula = eval_data$malaria ~ net_use_hat)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -0.504 -0.180 -0.180  0.496  0.820 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.74160    0.03757   19.74   &lt;2e-16 ***
## net_use_hat -0.72000    0.06273  -11.48   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.4463 on 998 degrees of freedom
## Multiple R-squared:  0.1166, Adjusted R-squared:  0.1157 
## F-statistic: 131.8 on 1 and 998 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><br> <br> <br> <br> <br></p>
<hr />
</div>
<div id="thinking-about-the-validity-of-instruments" class="section level2">
<h2>Thinking about the validity of instruments</h2>
<div class="figure">
<img src="https://raw.githubusercontent.com/seramirezruiz/stats-ii-lab/master/Session%205/data/validity_ivs.png" />

</div>
<p>
<p><strong>We can also adapt the ivreg() syntax to accomodate valid conditional instruments:</strong></p>
<center>
<strong>ivreg(Y ~ D + W | Z + W)</strong>
</center>
<p><br> <br> <br> <br> <br> <br></p>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>An F statistic is a value you get when you run an ANOVA test or a regression analysis to find out if the means between two populations are significantly different. It’s similar to a t-statistic from a t-test; A-T test will tell you if a single variable is statistically significant and an F test will tell you if a group of variables are jointly significant.<a href="#fnref1">↩</a></p></li>
</ol>
</div>

  </div>
  

<div class="navigation navigation-single">
    
    <a href="/2020-fall-stats2/scripts/lab_4_causal_graphs/" class="navigation-prev">
      <i aria-hidden="true" class="fa fa-chevron-left"></i>
      <span class="navigation-tittle">Session 03 - Causal Graphs</span>
    </a>
    
    
    <a href="/2020-fall-stats2/scripts/lab_6_matching/" class="navigation-next">
      <span class="navigation-tittle">Session 05 - Matching</span>
      <i aria-hidden="true" class="fa fa-chevron-right"></i>
    </a>
    
</div>


  

  
    


</article>


        </div>
        
    

<script defer src="https://use.fontawesome.com/releases/v5.12.1/js/all.js" integrity="sha384-ZbbbT1gw3joYkKRqh0kWyRp32UAvdqkpbLedQJSlnI8iLQcFVxaGyrOgOJiDQTTR" crossorigin="anonymous"></script>


    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/highlight.min.js"></script>
        
    <script type="text/javascript">
        
        hljs.initHighlightingOnLoad();
    </script>
    



    



    </body>
</html>
