<!DOCTYPE html>
<html lang="en">
    
    


    <head>
    <link href="https://gmpg.org/xfn/11" rel="profile">
    <meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<!-- Enable responsiveness on mobile devices -->
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">
<meta name="generator" content="Hugo 0.80.0" />

    
    
    

<title>Session 09 - Moderation • 2020-II Statistical Modeling and Causal Inference Tutorial</title>


<meta name="twitter:card" content="summary"/>
<meta name="twitter:title" content="Session 09 - Moderation"/>
<meta name="twitter:description" content="Measuring the effect of information on peace agreement support 
The country of Absurdistan has had an ongoing civil conflict for the past 60 years. The fighting between national government forces and guerrilla members from the National Revolutionary Army (NRA) has lead to more than 200,000 deaths, 8 million internally displaced persons, and countless victims between 1960 to 2020. The civil war in Absurdistan has been a low-intensity asymmetric war."/>

<meta property="og:title" content="Session 09 - Moderation" />
<meta property="og:description" content="Measuring the effect of information on peace agreement support 
The country of Absurdistan has had an ongoing civil conflict for the past 60 years. The fighting between national government forces and guerrilla members from the National Revolutionary Army (NRA) has lead to more than 200,000 deaths, 8 million internally displaced persons, and countless victims between 1960 to 2020. The civil war in Absurdistan has been a low-intensity asymmetric war." />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://seramirezruiz.github.io/2020-fall-stats2/scripts/lab_10_moderation/" />
<meta property="article:published_time" content="2020-11-03T00:00:00+00:00" />
<meta property="article:modified_time" content="2020-11-03T00:00:00+00:00" /><meta property="og:site_name" content="Statistical Modeling and Causal Inference Tutorial | 2020-II" />


    


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css">








<link rel="stylesheet" href="/2020-fall-stats2/scss/hyde-hyde.71157e768c4e111a23c3531b95e0cbb59bbef3c9e6901d36247cb53d6b6be258.css" integrity="sha256-cRV&#43;doxOERojw1MbleDLtZu&#43;88nmkB02JHy1PWtr4lg=">


<link rel="stylesheet" href="/2020-fall-stats2/scss/print.2744dcbf8a0b2e74f8a50e4b34e5f441be7cf93cc7de27029121c6a09f9e77bc.css" integrity="sha256-J0Tcv4oLLnT4pQ5LNOX0Qb58&#43;TzH3icCkSHGoJ&#43;ed7w=" media="print">



    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/apple-touch-icon-144-precomposed.png">
    <link rel="shortcut icon" href="/favicon.png">
    
    

</head>


    <body class=" ">
    

    <script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML"></script>
    
    <script type="text/x-mathjax-config">
    MathJax.Hub.Config({
        tex2jax: {
            inlineMath: [ ['$','$'], ["\\(","\\)"] ],
            displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
            processEscapes: true,
            processEnvironments: true
        },
        // Center justify equations in code and markdown cells. Elsewhere
        // we use CSS to left justify single line equations in code cells.
        displayAlign: 'center',
        "HTML-CSS": {
            styles: {'.MathJax_Display': {"margin": 0}},
            linebreaks: { automatic: true }
        }
    });
    </script>


<div class="sidebar">
  <div class="container ">
    <div class="sidebar-about">
      <span class="site__title">
        <a href="https://seramirezruiz.github.io/2020-fall-stats2">
        
          2020-II Statistical Modeling and Causal Inference Tutorial
        
        </a>
      </span>
      
      
      <p class="site__description">
        
      </p>
    </div>
    <div class="collapsible-menu">
      <input type="checkbox" id="menuToggle">
      <label for="menuToggle">2020-II Statistical Modeling and Causal Inference Tutorial</label>
      <div class="menu-content">
        <div>
	<ul class="sidebar-nav">
		 
		 
			 
				<li>
					<a href="/2020-fall-stats2/about/"><i class='fa fa-info'></i>
						<span>About</span>
					</a>
				</li>
			 
		 
			 
				<li>
					<a href="/2020-fall-stats2/scripts/"><i class='fa fa-code'></i>
						<span>Scripts</span>
					</a>
				</li>
			 
		
	</ul>
</div>

        <section class="social">
	
	<a href="https://twitter.com/seramirezruiz" rel="me"><i class="fab fa-twitter fa-lg" aria-hidden="true"></i></a>
	
	
	
	
	<a href="https://github.com/seramirezruiz" rel="me"><i class="fab fa-github fa-lg" aria-hidden="true"></i></a>
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	<a href="mailto:ramirez-ruiz@hertie-school.org" rel="me"><i class="fas fa-at fa-lg" aria-hidden="true"></i></a>
	
	
	
	
</section>

      </div>
    </div>
    
<div class="copyright">
  &copy; 2020 - 2021 Sebastian Ramirez Ruiz
  
    <a href="https://creativecommons.org/licenses/by-sa/4.0">CC BY-SA 4.0</a>
  
</div>



  </div>
</div>

        <div class="content container">
            
    
<article>
  <header>
    <h1>Session 09 - Moderation</h1>
    
    
<div class="post__meta">
    
    
      <i class="fas fa-calendar-alt"></i> Nov 3, 2020
    
    
    
    
    
    <br/>
    <i class="fas fa-clock"></i> 11 min read
</div>


  </header>
  
  
  <div class="post">
    
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>


<div id="measuring-the-effect-of-information-on-peace-agreement-support" class="section level2">
<h2>Measuring the effect of information on peace agreement support</h2>
<p><br> The country of Absurdistan has had an ongoing civil conflict for the past 60 years. The fighting between national government forces and guerrilla members from the National Revolutionary Army (NRA) has lead to more than 200,000 deaths, 8 million internally displaced persons, and countless victims between 1960 to 2020. The civil war in Absurdistan has been a low-intensity asymmetric war. The legacies of the conflict have been bore largely by regions in the periphery of the country. Large cities and industrial regions have been spared from most of the fighting.</p>
<p>The government and the leadership of the NRA reached a peace agreement a couple of months ago; however, the agreement has been received poorly by the general population of Absurdistan. The opposition party the Undemocratic Center (UC) has allegedly ran campaigns misrepresenting the contents of the agreement in partisan media outlets and social media.</p>
<p>The Special Envoy for Peace has established a taskforce to design a strategy to increase support for the peace agreement. Many in the taskforce suspect that if the public were properly informed about the agreement reached, the levels of support would be higher.</p>
<p>You are hired as a scientific consultant for the taskforce. You run a survey experiment on a sample of 1000 respondents. You randomly assign respondents to watch an educational 40 second video about the peace agreement. Here are the results:</p>
<p><br> <br></p>
<hr />
</div>
<div id="exploring-the-data" class="section level2">
<h2>1.1 Exploring the data</h2>
<pre class="r"><code>set.seed(42) #for consistent results

library(dplyr) # to wrangle our data
library(tidyr) # to wrangle our data - pivot_longer()
library(ggplot2) # to render our graphs
library(readr) # for loading the .csv data
library(kableExtra) # to render better formatted tables
library(stargazer) # for formatting your model output
library(margins) #for calculating MARGINAL/PARTIAL EFFECT
library(ggeffects) # easily calculating PREDICTIVE MARGINS

moderation_df &lt;- readr::read_csv(&quot;https://raw.githubusercontent.com/seramirezruiz/hertiestats2/master/data/moderation_df.csv&quot;) # simulated data
names(moderation_df) # to check the names of the variables in our data</code></pre>
<pre><code>## [1] &quot;subject_id&quot;          &quot;treatment&quot;           &quot;victim_verbose&quot;     
## [4] &quot;victim&quot;              &quot;female&quot;              &quot;female_verbose&quot;     
## [7] &quot;support_thermometer&quot;</code></pre>
<p><br> Our dataset <em>moderation_df</em>, contains the following information:</p>
<ul>
<li><code>subject_id</code>: A unique numeric identification for each respondent</li>
<li><code>treatment</code>: A binary marker for treatment</li>
<li><code>victim_verbose</code>: A verbose binary marker of the respondents' victimhood status (Not a Victim-Victim)</li>
<li><code>victim</code>: A numeric binary marker of the respondents' victimhood status (0-1)</li>
<li><code>female</code>: A numeric binary marker of the respondents' sex (0-1)</li>
<li><code>female_verbose</code>: A verbose binary marker of the respondents' sex (Male-Female)</li>
<li><code>support_thermometer</code>: A continuous measure of support for the agreement (0-100)</li>
</ul>
<p><br></p>
<div id="lets-explore-who-is-in-our-sample" class="section level4">
<h4>Let's explore who is in our sample</h4>
<p>
<p>We can use what we have learned about the base R <em>table()</em> function, to check who was in our sample:</p>
<pre class="r"><code>table(moderation_df$treatment) %&gt;% 
  knitr::kable(col.names = c(&quot;Treatment&quot;, &quot;Frequency&quot;)) %&gt;% # create kable table
  kableExtra::kable_styling() # view kable table</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Treatment
</th>
<th style="text-align:right;">
Frequency
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
0
</td>
<td style="text-align:right;">
500
</td>
</tr>
<tr>
<td style="text-align:left;">
1
</td>
<td style="text-align:right;">
500
</td>
</tr>
</tbody>
</table>
<pre class="r"><code>table(moderation_df$treatment, moderation_df$victim_verbose) %&gt;% 
  knitr::kable() %&gt;% # create kable table
  kableExtra::kable_styling() # view kable table</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Not a victim
</th>
<th style="text-align:right;">
Victim
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
0
</td>
<td style="text-align:right;">
250
</td>
<td style="text-align:right;">
250
</td>
</tr>
<tr>
<td style="text-align:left;">
1
</td>
<td style="text-align:right;">
250
</td>
<td style="text-align:right;">
250
</td>
</tr>
</tbody>
</table>
<p><br> <br></p>
</div>
<div id="lets-explore-visually-the-observed-levels-of-public-support-for-the-agreement" class="section level4">
<h4>Let's explore visually the observed levels of public support for the agreement</h4>
<p>
<pre class="r"><code>ggplot(moderation_df, aes(x = support_thermometer)) +
  geom_density(fill = &quot;#af8dc3&quot;, alpha = 0.5) +
  theme_minimal() +
  labs(x = &quot;Support thermometer&quot;,
       y = &quot;Density&quot;)</code></pre>
<p><img src="/scripts/lab_10_moderation_files/figure-html/unnamed-chunk-3-1.png" width="672" style="display: block; margin: auto;" /></p>
<center>
<strong>WHAT DO WE OBSERVE IN THIS GRAPH?</strong>
</center>
<p><br> <br></p>
</div>
<div id="lets-explore-visually-the-observed-levels-of-public-support-for-the-agreement-conditional-on-the-treatment-status" class="section level4">
<h4>Let's explore visually the observed levels of public support for the agreement conditional on the treatment status</h4>
<pre class="r"><code>ggplot(moderation_df, aes(x = support_thermometer, fill = factor(treatment))) +
  geom_density(alpha = 0.5) +
  theme_minimal() +
  labs(x = &quot;Support thermometer&quot;,
       y = &quot;Density&quot;,
       fill = &quot;Treatment&quot;) +
  theme(legend.position = &quot;bottom&quot;)</code></pre>
<p><img src="/scripts/lab_10_moderation_files/figure-html/unnamed-chunk-4-1.png" width="672" style="display: block; margin: auto;" /></p>
<center>
<strong>WHAT DO WE OBSERVE IN THIS GRAPH?</strong>
</center>
<p><br> <br></p>
</div>
<div id="lets-explore-visually-the-observed-levels-of-public-support-for-the-agreement-conditional-on-the-treatment-and-victimhood-status" class="section level4">
<h4>Let's explore visually the observed levels of public support for the agreement conditional on the treatment and victimhood status</h4>
<pre class="r"><code>ggplot(moderation_df, aes(x = support_thermometer, fill = factor(treatment))) +
  geom_density(alpha = 0.5) +
  facet_wrap(victim_verbose~treatment, nrow = 4) +
  theme_bw() +
  labs(x = &quot;Support thermometer&quot;,
       y = &quot;Density&quot;,
       fill = &quot;Treatment&quot;) +
  theme(legend.position = &quot;bottom&quot;)</code></pre>
<p><img src="/scripts/lab_10_moderation_files/figure-html/unnamed-chunk-5-1.png" width="672" style="display: block; margin: auto;" /></p>
<center>
<strong>WHAT DO WE OBSERVE IN THIS GRAPH?</strong>
</center>
<p><br> <br></p>
<hr />
<p><br> <br></p>
</div>
</div>
<div id="modeling-and-estimating" class="section level2">
<h2>1.2 Modeling and estimating</h2>
<p>During this week's lecture, we learned that we can explicitly model heterogeneity in treatment effects for subgroups. Thus, we can address the tension between having to do inference at the group level, and the recognition of individual differences.</p>
<p>The analysis of heterogeneity can be very important for the design of our strategy. There are competing theories about the effects of conflict victimization on political behavior and attitudes. Some of the literature points to victims developing pro-social attitudes, while others suggest that victims become intransigent towards out-groups. <strong>Could factual information about the peace agreement be received differently by victims and non-victims?</strong></p>
<p><br> <br></p>
<div id="how-to-estimate-heterogenous-treatment-effects" class="section level4">
<h4>How to estimate heterogenous treatment effects</h4>
<p>Heterogeneous treatment effects are usually estimated with regression models that include an interaction between the treatment and the moderator. In our case, the formula would look like this:</p>
<span class="math display">\[Y_{i} = β_0 + β_1D_{i} + β_2Victim_{i} + β_3D_i * Victim_{i}+ ϵ_i  \]</span>
<p>
<ul>
<li><span class="math inline">\(β_0\)</span>: Constant
<p></li>
<li><span class="math inline">\(β_1\)</span>: Effect of <span class="math inline">\(D_i\)</span> on <span class="math inline">\(Y_i\)</span> if <span class="math inline">\(Victim_i\)</span> is zero
<p></li>
<li><span class="math inline">\(β_2\)</span>: Effect of <span class="math inline">\(Victim_i\)</span> on <span class="math inline">\(Y_i\)</span> if <span class="math inline">\(D_i\)</span> is zero
<p></li>
<li><span class="math inline">\(β_3\)</span>: Difference in treatment effects of <span class="math inline">\(D_i\)</span> depending on <span class="math inline">\(Victim_i\)</span></li>
</ul>
<p><br></p>
<p>or in <code>lm()</code> terms:</p>
<pre class="r"><code>lm(outcome ~ treatment + moderator + (treatment*moderator))
lm(outcome ~ treatment + moderator + treatment:moderator)
lm(outcome ~ treatment * moderator)</code></pre>
<p><br></p>
<hr />
<p><br></p>
</div>
<div id="lets-model-our-results" class="section level4">
<h4>Let's model our results</h4>
We will move forward by creating two models:
<p>
<ul>
<li>A <strong>naive model</strong>, where we will regress <code>support_thermometer</code> on <code>treatment</code>.</li>
<li>An <strong>interaction model</strong>, where we will add an interaction between <code>treatment</code> and <code>victim</code></li>
</ul>
<p><br> <br></p>
<hr />
<p><br> <br></p>
</div>
<div id="naive-modeling" class="section level3">
<h3>1.2.1 Naive modeling</h3>
<p>
<pre class="r"><code>naive_model &lt;- lm(support_thermometer ~ treatment, data = moderation_df)</code></pre>
<div align="center">
<pre class="r"><code>stargazer::stargazer(naive_model, type = &quot;text&quot;)</code></pre>
<pre><code>## 
## ===============================================
##                         Dependent variable:    
##                     ---------------------------
##                         support_thermometer    
## -----------------------------------------------
## treatment                    18.898***         
##                               (1.026)          
##                                                
## Constant                     35.055***         
##                               (0.725)          
##                                                
## -----------------------------------------------
## Observations                   1,000           
## R2                             0.254           
## Adjusted R2                    0.253           
## Residual Std. Error      16.220 (df = 998)     
## F Statistic          339.360*** (df = 1; 998)  
## ===============================================
## Note:               *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
<p><br></p>
<center>
<strong>WHAT DOES THIS MODEL TELL US?</strong>
</center>
<p>
<p>The naive model suggests that the subjects that the support for the peace agreement is about 18.9 percentage points higher on average for the subjects that watched the educational video. We suspect, however, that the video may affect differently victims from non-victims of the conflict.</p>
<p><br></p>
<div id="here-is-a-visual-illustration-of-the-values-rendered-by-the-naive-regression" class="section level4">
<h4>Here is a visual illustration of the values rendered by the naive regression</h4>
<pre class="r"><code>ggplot(moderation_df, aes(x = support_thermometer, fill = factor(treatment))) +
  geom_density(alpha = 0.5) +
  theme_minimal() +
  geom_vline(xintercept = 35.055, linetype = &quot;longdash&quot;, color = &quot;red&quot;) + #D=0
  geom_vline(xintercept = 35.055 + 18.898, linetype = &quot;longdash&quot;, color = &quot;darkblue&quot;) + #D=1
  labs(x = &quot;Support thermometer&quot;,
       y = &quot;Density&quot;,
       fill = &quot;Treatment&quot;) +
  theme(legend.position = &quot;bottom&quot;)</code></pre>
<p><img src="/scripts/lab_10_moderation_files/figure-html/unnamed-chunk-8-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><br> <br></p>
<hr />
<p><br> <br></p>
</div>
</div>
<div id="interaction-model" class="section level3">
<h3>1.2.2 Interaction model</h3>
<p>
<p>Following any of the different formats renders the same results.</p>
<pre class="r"><code>interaction_model &lt;- lm(support_thermometer ~ treatment + victim + (treatment*victim), data = moderation_df)
interaction_model_2 &lt;- lm(support_thermometer ~ treatment + victim + treatment:victim, data = moderation_df)
interaction_model_3 &lt;- lm(support_thermometer ~ treatment*victim, data = moderation_df)</code></pre>
<div align="center">
<pre class="r"><code>stargazer::stargazer(interaction_model, interaction_model_2, interaction_model_3, type = &quot;text&quot;)</code></pre>
<pre><code>## 
## =====================================================================
##                                         Dependent variable:          
##                                --------------------------------------
##                                         support_thermometer          
##                                    (1)          (2)          (3)     
## ---------------------------------------------------------------------
## treatment                        8.013***     8.013***     8.013***  
##                                  (0.776)      (0.776)      (0.776)   
##                                                                      
## victim                          14.256***    14.256***    14.256***  
##                                  (0.776)      (0.776)      (0.776)   
##                                                                      
## treatment:victim                21.771***    21.771***    21.771***  
##                                  (1.097)      (1.097)      (1.097)   
##                                                                      
## Constant                        27.927***    27.927***    27.927***  
##                                  (0.549)      (0.549)      (0.549)   
##                                                                      
## ---------------------------------------------------------------------
## Observations                      1,000        1,000        1,000    
## R2                                0.787        0.787        0.787    
## Adjusted R2                       0.786        0.786        0.786    
## Residual Std. Error (df = 996)    8.673        8.673        8.673    
## F Statistic (df = 3; 996)      1,227.193*** 1,227.193*** 1,227.193***
## =====================================================================
## Note:                                     *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
<p><br></p>
<center>
<strong>WHAT DOES THIS MODEL TELL US?</strong>
</center>
<p>
<ul>
<li><span class="math inline">\(β_0\)</span>: Constant = The average support for non-victims who were not exposed to the video was 27.92
<p></li>
<li><span class="math inline">\(β_1\)</span>: Effect of <span class="math inline">\(D_i\)</span> on <span class="math inline">\(Y_i\)</span> if <span class="math inline">\(Victim_i\)</span> is zero = The educational video results in an increase of about 8 percentage points of the peace agreement for the non-victims
<p></li>
<li><span class="math inline">\(β_2\)</span>: Effect of <span class="math inline">\(Victim_i\)</span> on <span class="math inline">\(Y_i\)</span> if <span class="math inline">\(D_i\)</span> is zero = On average, victims’ support for the peace agreement is 14.3 percentage points higher than that of the non-victims in the control group
<p></li>
<li><span class="math inline">\(β_3\)</span>: Difference in treatment effects of <span class="math inline">\(D_i\)</span> depending on <span class="math inline">\(Victim_i\)</span> = The educational video results in an additional increase for victims of about 21.8 percentage points, compared to the effect for non-victims <br></li>
</ul>
<p><br></p>
<div id="here-is-a-visual-illustration-of-the-values-rendered-by-the-model-with-interaction-terms" class="section level4">
<h4>Here is a visual illustration of the values rendered by the model with interaction terms</h4>
<pre class="r"><code>moderation_df %&gt;%
  dplyr::group_by(treatment,victim_verbose) %&gt;%
  dplyr::mutate(avg_support = mean(support_thermometer)) %&gt;%
ggplot(., aes(x = support_thermometer, fill = factor(treatment))) +
  geom_density(alpha = 0.5) +
  geom_vline(aes(xintercept = avg_support), linetype = &quot;longdash&quot;) +
  facet_wrap(victim_verbose~treatment, nrow = 4) +
  theme_bw() +
  labs(x = &quot;Support thermometer&quot;,
       y = &quot;Density&quot;,
       fill = &quot;Treatment&quot;) +
  theme(legend.position = &quot;bottom&quot;)</code></pre>
<p><img src="/scripts/lab_10_moderation_files/figure-html/unnamed-chunk-11-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><br> <br></p>
<hr />
<p><br> <br></p>
</div>
</div>
</div>
<div id="extracting-marginalpartial-effects-from-our-interaction-models" class="section level2">
<h2>1.3. Extracting marginal/partial effects from our interaction models</h2>
<p>For this portion, we are interested in <strong>marginal/partial effects</strong>, which we will extract through the <code>margins()</code> function from the <code>margins</code> package.</p>
<p>Some packages in <strong>R</strong> aimed at rendering <strong>marginal effects</strong> do render the <strong>predictive margins</strong> instead. For the purposes of the class, when asked to render marginal or partial effects you are expected to render them as introduced in the lecture (i.e., <span class="math inline">\(\frac{\partial Y_i}{\partial {D}_i}\)</span>). When asked for this, you will utilize <code>margins()</code>.</p>
<p>You can check the documentation <a href="http://cran.uni-muenster.de/web/packages/margins/vignettes/Introduction.html">here</a>. The syntax for the <code>margins()</code> function for extracting partial effects of the treatment at different levels of the moderator is the following:</p>
<pre class="r"><code>margins::margins(name_of_your_model, variables = &quot;treatment_var&quot;, at = list(moderator_variable = values))</code></pre>
<p>Let's say we are interested in the <strong>marginal/partial effect</strong> of our video treatment for victims and non-victims. We would do:</p>
<pre class="r"><code>summary(margins::margins(interaction_model, variables = &quot;treatment&quot;, at = list(victim = 0:1)))</code></pre>
<pre><code>##     factor victim     AME     SE       z      p   lower   upper
##  treatment 0.0000  8.0125 0.7757 10.3288 0.0000  6.4921  9.5330
##  treatment 1.0000 29.7831 0.7758 38.3895 0.0000 28.2626 31.3037</code></pre>
<p><br></p>
<div id="lets-plot-the-the-marginalpartial-effect-of-the-treatment-for-victims-and-non-victims" class="section level4">
<h4>Let's plot the the marginal/partial effect of the treatment for victims and non-victims</h4>
<pre class="r"><code>pe_margins &lt;- margins::margins(interaction_model, variables = &quot;treatment&quot;, at = list(victim = 0:1))

pe_plotting &lt;- summary(pe_margins) %&gt;% #NOTE we use the summary output, instead of the margins object
  dplyr::select(victim, AME, lower, upper) %&gt;% # you will need to adapt this based your moderator
  dplyr::mutate(victim_labels = ifelse(victim == 1, &quot;Victim&quot;, &quot;No Victim&quot;)) # you will need to adapt this based your moderator

ggplot(pe_plotting, aes(x = victim_labels,
                        y = AME)) +
  geom_point(size = 1.5) +
  geom_segment(aes(x = victim_labels, xend = victim_labels, y = lower, yend = upper), size = 0.5) + # render whiskers from confidence intervals
  theme_minimal() +
  scale_y_continuous(limits = c(0,45)) + # you may need to change the limits for your plots
  labs(x = &quot;Respondent status\n&quot;,
       y = &quot;\nPartial effect of educational video&quot;, 
       caption = &quot;Note: You can utilize it to describe what the plot illustrates during your assignment.&quot;) + 
  coord_flip()</code></pre>
<p><img src="/scripts/lab_10_moderation_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p><br> <br></p>
<hr />
<p><br> <br></p>
</div>
</div>
<div id="extracting-predictive-margins-from-our-interaction-models" class="section level2">
<h2>1.4. Extracting predictive margins from our interaction models</h2>
<p>For this portion, we are interested in <strong>predictive margins</strong>. In here, our interest is to return the expectation for each level of a predictor. We will extract this through the <code>ggeffects()</code> function from the <code>ggeffects</code> package. You can check the documentation <a href="https://strengejacke.github.io/ggeffects/index.html">here</a>. The syntax is the following:</p>
<pre class="r"><code>ggeffects::ggeffect(name_of_your_model, terms = c(&quot;termA&quot;, &quot;termB&quot;))</code></pre>
<p>Let's say we are interested in the <strong>predictive margins</strong> for all out victim and treatment permutations. We would do:</p>
<pre class="r"><code>ggeffects::ggeffect(interaction_model, terms = c(&quot;victim&quot;,&quot;treatment&quot;))</code></pre>
<pre><code>## 
## # Predicted values of support_thermometer
## # x = victim
## 
## # treatment = 0
## 
## x | Predicted |   SE |         95% CI
## -------------------------------------
## 0 |     27.93 | 0.55 | [26.85, 29.00]
## 1 |     42.18 | 0.55 | [41.11, 43.26]
## 
## # treatment = 1
## 
## x | Predicted |   SE |         95% CI
## -------------------------------------
## 0 |     35.94 | 0.55 | [34.86, 37.02]
## 1 |     71.97 | 0.55 | [70.89, 73.04]</code></pre>
<p><br></p>
<div id="lets-plot-these-predictive-margins" class="section level4">
<h4>Let's plot these predictive margins</h4>
<p>In this exercise we will meet a very important function from <code>dplyr</code>, <code>dplyr::case_when()</code>. <strong>This function allows us to vectorize multiple ifelse() statements</strong>. The syntax is the following:</p>
<pre class="r"><code>dplyr::case_when(condition ~ what to do if met)</code></pre>
<p>Let's see it at play.</p>
<pre class="r"><code>extracted_me &lt;-  ggeffects::ggeffect(interaction_model, terms = c(&quot;victim&quot;,&quot;treatment&quot;)) %&gt;%
  dplyr::mutate(group_labels = dplyr::case_when(x == 1 &amp; group == 1 ~ &quot;Victim (1) - Treatment (1)&quot;,
                                                x == 1 &amp; group == 0 ~ &quot;Victim (1) - Treatment (0)&quot;,
                                                x == 0 &amp; group == 1 ~ &quot;Victim (0) - Treatment (1)&quot;,
                                                x == 0 &amp; group == 0 ~ &quot;Victim (0) - Treatment (0)&quot;
  )) # adding labels to x groups to plot

extracted_me</code></pre>
<pre><code>## 
## # Predicted values of support_thermometer
## # x = victim
## 
## # treatment = 0
## 
## x | Predicted |   SE |               group_labels |         95% CI
## ------------------------------------------------------------------
## 0 |     27.93 | 0.55 | Victim (0) - Treatment (0) | [26.85, 29.00]
## 1 |     42.18 | 0.55 | Victim (1) - Treatment (0) | [41.11, 43.26]
## 
## # treatment = 1
## 
## x | Predicted |   SE |               group_labels |         95% CI
## ------------------------------------------------------------------
## 0 |     35.94 | 0.55 | Victim (0) - Treatment (1) | [34.86, 37.02]
## 1 |     71.97 | 0.55 | Victim (1) - Treatment (1) | [70.89, 73.04]</code></pre>
<pre class="r"><code>ggplot(extracted_me, aes(x = group_labels, 
                         y= predicted, 
                         fill = group_labels)) +
  geom_bar(stat = &quot;identity&quot;, 
           alpha = 0.5) + # we set dodge instead of default stacked
  geom_point(size = 1.5) +
  geom_segment(aes(x = group_labels, 
                   xend = group_labels, 
                   y = conf.high, 
                   yend = conf.low), size = 0.5) + # render whiskers from confidence intervals
  theme_minimal() +
  labs(x = &quot;\nRespondent status&quot;,
       y = &quot;Effect of educational video&quot;,
       fill = &quot;Treatment&quot;,
       caption = &quot;Note: You can utilize it to describe what the plot illustrates during your assignment.&quot;) +
  theme(legend.position = &quot;none&quot;)</code></pre>
<p><img src="/scripts/lab_10_moderation_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p><br> <br></p>
<hr />
<p><br> <br></p>
</div>
</div>
<div id="drafting-some-brief-recommedations" class="section level2">
<h2>1.4 Drafting some brief recommedations</h2>
After conducting your experiment, you report back to the taskforce. Based on your results, you suggest that the educational videos may be a useful tool to encourage the wider public to hold a warmer opinion about the peace agreement. You also tell the taskforce that, although the videos have an average positive effect, they affect with a higher intensity victims of the conflict. You suggest to develop alternative strategies to tackle the non-victims, so that they do not fall through the cracks.
<p>
<p><br></p>
<center>
<img src="https://media.giphy.com/media/rrLt0FcGrDeBq/giphy.gif" alt="peace" width="450"/>
</center>
</div>

  </div>
  

<div class="navigation navigation-single">
    
    <a href="/2020-fall-stats2/scripts/lab_9_panel_data_fe/" class="navigation-prev">
      <i aria-hidden="true" class="fa fa-chevron-left"></i>
      <span class="navigation-tittle">Session 08 - Panel Data and Fixed Effects Specifications</span>
    </a>
    
    
</div>


  

  
    


</article>


        </div>
        
    

<script defer src="https://use.fontawesome.com/releases/v5.12.1/js/all.js" integrity="sha384-ZbbbT1gw3joYkKRqh0kWyRp32UAvdqkpbLedQJSlnI8iLQcFVxaGyrOgOJiDQTTR" crossorigin="anonymous"></script>


    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/highlight.min.js"></script>
        
    <script type="text/javascript">
        
        hljs.initHighlightingOnLoad();
    </script>
    



    



    </body>
</html>
